# Generated by Django 5.1.1 on 2024-10-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dica'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dica',
        ),
        migrations.RenameField(
            model_name='historicoteste',
            old_name='data_realizacao',
            new_name='data_teste',
        ),
        migrations.RenameField(
            model_name='historicoteste',
            old_name='erros',
            new_name='erros_total',
        ),
        migrations.RenameField(
            model_name='historicoteste',
            old_name='tempo',
            new_name='tempo_total',
        ),
        migrations.RemoveField(
            model_name='historicoteste',
            name='texto',
        ),
        migrations.AddField(
            model_name='historicoteste',
            name='frases',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultadosteste',
            name='tempo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadosteste',
            name='acertos',
            field=models.IntegerField(default=0),
        ),
    ]
