# Generated by Django 5.1.1 on 2024-10-24 15:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_data_teste_historicoteste_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoteste',
            name='palavras_por_minuto',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='historicoteste',
            name='tempo_total',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='resultadosteste',
            name='teste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.historicoteste'),
        ),
    ]
